export const actions = {
  setTick: 'setTick',
  stopTick: 'stopTick',
  clockTick: 'clockTick',
  fall: 'fall',
  fallIfFalling: 'fallIfFalling',
  setNextBlo: 'setNextBlo',
  useNextBlo: 'useNextBlo',
  clearInput: 'clearInput',
  inpLR: 'inpLR',
  inpRR: 'inpRR',
  inpL: 'inpL',
  inpR: 'inpR',
  inpD: 'inpD',
  leftRot: 'leftRot',
  riteRot: 'riteRot',
  left: 'left',
  rite: 'rite',
  down: 'down',
  clearCompletedRows: 'clearCompletedRows',
  reset: 'reset',
  setBucket: 'setBucket',
  toggleMatrixStyle: 'toggleMatrixStyle',
  setupNewGame: 'setupNewGame',
  toggleMusic: 'toggleMusic'
}
